// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

#ifndef PROTOBUF_header_2eproto__INCLUDED
#define PROTOBUF_header_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dataheader {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_header_2eproto();
void protobuf_AssignDesc_header_2eproto();
void protobuf_ShutdownFile_header_2eproto();

class header;

// ===================================================================

class header : public ::google::protobuf::Message {
 public:
  header();
  virtual ~header();

  header(const header& from);

  inline header& operator=(const header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const header& default_instance();

  void Swap(header* other);

  // implements Message ----------------------------------------------

  header* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const header& from);
  void MergeFrom(const header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 totalsize = 1;
  inline bool has_totalsize() const;
  inline void clear_totalsize();
  static const int kTotalsizeFieldNumber = 1;
  inline ::google::protobuf::int32 totalsize() const;
  inline void set_totalsize(::google::protobuf::int32 value);

  // required int32 bodyheadersize = 2;
  inline bool has_bodyheadersize() const;
  inline void clear_bodyheadersize();
  static const int kBodyheadersizeFieldNumber = 2;
  inline ::google::protobuf::int32 bodyheadersize() const;
  inline void set_bodyheadersize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataheader.header)
 private:
  inline void set_has_totalsize();
  inline void clear_has_totalsize();
  inline void set_has_bodyheadersize();
  inline void clear_has_bodyheadersize();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 totalsize_;
  ::google::protobuf::int32 bodyheadersize_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_header_2eproto();
  friend void protobuf_AssignDesc_header_2eproto();
  friend void protobuf_ShutdownFile_header_2eproto();

  void InitAsDefaultInstance();
  static header* default_instance_;
};
// ===================================================================


// ===================================================================

// header

// required int32 totalsize = 1;
inline bool header::has_totalsize() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void header::set_has_totalsize() {
  _has_bits_[0] |= 0x00000001u;
}
inline void header::clear_has_totalsize() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void header::clear_totalsize() {
  totalsize_ = 0;
  clear_has_totalsize();
}
inline ::google::protobuf::int32 header::totalsize() const {
  return totalsize_;
}
inline void header::set_totalsize(::google::protobuf::int32 value) {
  set_has_totalsize();
  totalsize_ = value;
}

// required int32 bodyheadersize = 2;
inline bool header::has_bodyheadersize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void header::set_has_bodyheadersize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void header::clear_has_bodyheadersize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void header::clear_bodyheadersize() {
  bodyheadersize_ = 0;
  clear_has_bodyheadersize();
}
inline ::google::protobuf::int32 header::bodyheadersize() const {
  return bodyheadersize_;
}
inline void header::set_bodyheadersize(::google::protobuf::int32 value) {
  set_has_bodyheadersize();
  bodyheadersize_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dataheader

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_header_2eproto__INCLUDED
